### ISSUE TITLE
General remarks

### ISSUE THREAD

**Issue by okbalefthanded** [Sehaba95/Algiers-Apartment-Price-Prediction#1]
Before checking the code and going deeper, I'll point out to the Readme file:

1- In regression, the score that's calculated for the model's performance is not the classification accuracy, it's the R^2 coefficient. change the 2nd columns title in the first table.

2 - the 2nd and 3rd columns in the Data profiling table show redundant data dimension that's already mentioned in the file's head, you can delete them and keep only the columns on data statistics.

Good luck with the next steps on making the models better.

**Comment by Sehaba95** [comment]
Thanks.

Do you have any suggestion on how to make the models better?

**Comment by okbalefthanded** [comment]
The raw data are hard for all the models to train and make prediction. First, as I noticed in the correlation table, the features "Superificie" and "Piece" are highly correlated, in this case linear models fail since they struggle with highly correlated variables, you can discard the feature "piece" from the data.

The plots clearly show that the data have not a familiar pattern that can give us insights easily, so what I suggest is to look for transformation for data (other than preprocessing techniques like normalization) to hand engineer meaningful features that will be easier to make prediction with.
